const projects=[
 {n:"01",id:"jai",title:"JAI — AI Career & Life Guide",meta:"0→1 product · AI experience · Product strategy",copy:"Reimagining career guidance as a trusted conversation—taking JAI from discovery and PRD through AI personality, journey architecture, MVP definition, UI and a live voice prototype.",tags:"Product strategy / PRD / AI UX / Conversation design / UI",art:"JAI / 0→1",tone:"jai",live:"https://jaro.zipteams.com/"},
 {n:"02",id:"ats",title:"ATS Resume Checker",meta:"Product concept · UX strategy · UI design",copy:"Reframing a utility tool as a lead-conversion experience—combining resume scoring, useful insights and a clear conversion journey.",tags:"Product thinking / AI product / Conversion UX",art:"ATS / 92",tone:"pink",live:"https://atsresumechecker.jaroeducation.com/"},
 {n:"03",id:"landing-pages",title:"Landing Page Ecosystem",meta:"Experience ownership · Design operations",copy:"Owning the landing-page journey from brief and content alignment through responsive design, development handoff, QA and launch.",tags:"UI/UX / Design systems / Stakeholders / QA",art:"LP / SYSTEM",tone:"cream"},
 {n:"04",id:"jaro-connect",title:"Jaro Connect — Phase 1 & 2",meta:"Live mobile product · Product evolution",copy:"From shipping the learner app across iOS and Android to shaping its next career-focused ecosystem.",tags:"Mobile UX / Design system / Product discovery",art:"APP / LIVE",tone:"lilac",live:"https://play.google.com/store/apps/details?id=com.newest.jaroeducation",secondary:"https://apps.apple.com/in/app/jaroconnect/id6447189924"},
 {n:"05",id:"notion-ga4",title:"Notion × GA4 Intelligence",meta:"Automation · Product operations",copy:"A reusable reporting pipeline that moves analytics into Notion and turns weekly performance data into an AI-assisted narrative.",tags:"Systems thinking / Make / GA4 / Gemini",art:"DATA / FLOW",tone:"mint"}
];
export default function Home(){return <main>
 <header><a className="brand" href="#top"><b>J<span>.</span></b><i><strong>JASMEET KAUR</strong><small>PRODUCT DESIGNER</small></i></a><nav><a href="#work">Work</a><a href="#about">About</a><a className="cta" href="#contact">Let&apos;s talk ↗</a></nav></header>
 <section id="top" className="hero"><img src="/jasmeet-impact-hero-clean-16x9.png" alt="Jasmeet Kaur, Product Designer — creating real impact"/><div className="hero-scan" aria-hidden="true"/><span className="hero-spark spark-one" aria-hidden="true">✦</span><a className="sticker" href="#work">SEE MY<br/>WORK ↓</a></section>
 <div className="ticker"><div className="ticker-track"><span>PRODUCT THINKING ✦ UI/UX DESIGN ✦ CONVERSION EXPERIENCES ✦ END-TO-END OWNERSHIP ✦ AI PROTOTYPING ✦ DESIGN OPERATIONS ✦ </span><span aria-hidden="true">PRODUCT THINKING ✦ UI/UX DESIGN ✦ CONVERSION EXPERIENCES ✦ END-TO-END OWNERSHIP ✦ AI PROTOTYPING ✦ DESIGN OPERATIONS ✦ </span></div></div>
 <section id="work" className="work pad"><div className="intro"><span>SELECTED WORK / 2025—26</span><h1>Big problems.<br/><em>Clear experiences.</em></h1><p>I work where user needs, business goals and execution meet.</p></div>
 <div className="projects">{projects.map(p=><article key={p.title} className={`${p.tone} reveal`}><div className="meta"><b>{p.n}</b><span>{p.meta}</span></div><div className="project-grid"><div><h2>{p.title}</h2><p>{p.copy}</p><small>{p.tags}</small><div className="project-actions"><a className="case-link" href={`#case-${p.id}`}>Read the case study ↓</a>{p.live&&<a className="live-link" href={p.live} target="_blank" rel="noreferrer">{p.id==="jaro-connect"?"Play Store ↗":"View live project ↗"}</a>}{p.secondary&&<a className="live-link" href={p.secondary} target="_blank" rel="noreferrer">App Store ↗</a>}</div></div><div className="art"><b>{p.art}</b><i>↗</i></div></div></article>)}</div></section>
 <section className="case-studies">
  <article id="case-jai" className="case case-jai">
   <div className="case-rail"><span>CASE STUDY 01</span><b>JAI</b><small>0→1 product strategy<br/>AI experience design<br/>MVP definition</small></div>
   <div className="case-body"><a className="case-close" href="#work" aria-label="Close JAI case study">Close ×</a>
    <div className="jai-orb"><video autoPlay muted loop playsInline src="/jai-logo.mp4"/><div><span>0→1 / AI PRODUCT</span><h2>What if career guidance started with a <em>conversation?</em></h2><p>I took JAI from product discovery to a working AI experience: framing the opportunity, writing the PRD, defining the MVP, architecting the journey, designing JAI&apos;s personality and guardrails, shaping the UI and bringing the concept to life as a voice-enabled prototype.</p><a href="https://jaro.zipteams.com/" target="_blank" rel="noreferrer">Talk to the live prototype ↗</a></div></div>
    <div className="case-facts"><div><small>MY ROLE</small><p>Product strategy, product definition, UX architecture, AI conversation design, UI/UX and prototyping.</p></div><div><small>THE PRODUCT</small><p>An AI career & learning companion that understands goals first, then helps learners explore programmes without sales pressure.</p></div><div><small>NORTH STAR</small><p>The power of choice stays with the learner. Success means helping someone make a decision they understand and trust.</p></div></div>
    <div className="case-chapter"><span>01 / DISCOVERY</span><h3>Course discovery was behaving like a catalogue when the decision was deeply personal.</h3><p>The existing path pushed learners through dozens of courses, comparison friction, long forms and a callback. I reframed the problem around clarity: understand the person before asking them to understand the catalogue.</p></div>
    <div className="story-strip"><div><small>USER PROBLEM</small><b>Too many options. Too little confidence.</b></div><div><small>PRODUCT BET</small><b>Conversation first. Search second. Courses third. Forms last.</b></div><div><small>BUSINESS OPPORTUNITY</small><b>Higher-intent leads, lower funnel friction and better-qualified conversations.</b></div></div>
    <div className="jai-methods"><span>Double Diamond</span><span>JTBD framing</span><span>5 Whys</span><span>Opportunity mapping</span><span>PRD</span><span>MoSCoW</span><span>Journey architecture</span><span>AI guardrails</span><span>North Star + KPIs</span><span>MVP roadmap</span></div>
    <div className="case-chapter"><span>02 / PRODUCT DEFINITION</span><h3>I turned the idea into a product system, not a chatbot feature.</h3><p>The PRD defined the vision, problem, audiences, product principles, objectives, success signals, MVP and future vision. Scope was deliberately constrained: conversational intake, skill-gap mapping and personalised recommendations were must-haves; broader coaching and multilingual support were held beyond v1.</p></div>
    <div className="decision-grid"><div><b>01</b><h4>Guide, never push</h4><p>Recommendations serve learner goals rather than a sales quota.</p></div><div><b>02</b><h4>Explain every choice</h4><p>JAI gives the reasoning behind a recommendation, not just the answer.</p></div><div><b>03</b><h4>Know the boundary</h4><p>When confidence or complexity crosses the AI&apos;s limit, the experience hands off to a human counsellor.</p></div></div>
    <div className="jai-visual"><img src="/jai-persona.jpeg" alt="JAI AI persona, behaviour and communication system" loading="lazy"/><div><span>03 / AI PERSONA & GOVERNANCE</span><h3>Designing the intelligence meant designing its character.</h3><p>JAI is intentionally calm, objective, warm and non-judgmental. I defined tone, humour, language mirroring, signature lines, behavioural rules and explicit never-do behaviours so the experience feels trustworthy rather than sales-driven.</p></div></div>
    <div className="case-chapter"><span>04 / SYSTEM ARCHITECTURE</span><h3>One journey, multiple ways forward.</h3><p>The architecture connects explicit search and conversational discovery into the same reasoning layer. Recommendations lead to a decision point: continue exploring, finalise a course, or leave. Assisted and self-guided checkout paths converge on enrolment, while drop-off feeds a respectful follow-up path.</p></div>
    <figure className="jai-journey"><img src="/jai-user-journey.png" alt="JAI user journey and AI reasoning architecture" loading="lazy"/><figcaption>JAI user journey: search + conversation → reasoning engine → personalised recommendations → decision → assisted or self-guided path.</figcaption></figure>
    <div className="case-chapter"><span>05 / EXPERIENCE DESIGN</span><h3>From architecture to something you can actually talk to.</h3><p>The interface carries the same personality as the product principles: focused, calm, conversational and transparent. Motion gives JAI presence without turning the assistant into a mascot that competes with the user&apos;s decision.</p></div>
    <div className="jai-videos"><video controls muted playsInline src="/jai-ui-1.mp4"/><video controls muted playsInline src="/jai-ui-2.mp4"/><video controls muted playsInline src="/jai-ui-3.mp4"/></div>
    <div className="case-outcome jai-outcome"><span>06 / PROTOTYPE</span><h3>A product thesis became a voice-enabled experience.</h3><p>The final prototype lets the idea move beyond static screens. It demonstrates JAI as a conversational AI presence and gives the product direction something stakeholders can experience, question and iterate on.</p><a className="outcome-link" href="https://jaro.zipteams.com/" target="_blank" rel="noreferrer">Experience JAI live ↗</a></div>
    <div className="jai-brand"><div><span>07 / BRAND WORLD</span><h3>Then JAI escaped the screen.</h3><p>The animated orb became a visual signature, extending into a physical hoodie concept. It is a small piece of world-building around the product: a digital identity with enough character to become culture.</p><b>INNOVATE &amp; EVOLVE</b></div><img src="/jai-hoodie.png" alt="JAI Innovate and Evolve hoodie design" loading="lazy"/></div>
    <div className="case-chapter"><span>08 / MEASUREMENT & NEXT</span><h3>Define success before claiming it.</h3><p>The proposed North Star is the share of learners reaching enrolment through a JAI conversation. Supporting signals include conversation completion, recommendation acceptance, time-to-recommendation, trust rating, qualified leads, application starts, conversion and handoff behaviour. These remain validation targets until measured in production.</p></div>
    <div className="jai-roadmap"><span>DISCOVERY</span><i>→</i><span>RESEARCH</span><i>→</i><span>PRD</span><i>→</i><span>UX STRATEGY</span><i>→</i><span>IA</span><i>→</i><span>WIREFRAMES</span><i>→</i><span>UI SYSTEM</span><i>→</i><strong>MVP</strong></div>
    <div className="case-outcome"><span>REFLECTION</span><p>JAI changed the shape of the problem for me. The challenge was not “how do we add AI?” It was how to make a consequential decision feel clearer without letting AI become another source of pressure. The next step is evidence: validate recommendation trust, conversational drop-off, handoff quality and which future capabilities genuinely improve decisions.</p></div>
   </div>
  </article>
  <article id="case-ats" className="case case-dark">
   <div className="case-rail"><span>CASE STUDY 01</span><b>ATS</b><small>Product concept<br/>UX strategy<br/>UI design</small></div>
   <div className="case-body"><a className="case-close" href="#work" aria-label="Close ATS Resume Checker case study">Close ×</a>
    <div className="case-hero"><span>01 / THE OPPORTUNITY</span><h2>From a score checker to a <em>lead-conversion product.</em></h2><p>The initial requirement could have ended as a simple upload-and-score utility. I saw an opportunity to make the experience genuinely useful for job seekers while creating a stronger acquisition journey for the business.</p></div>
    <div className="case-facts"><div><small>MY ROLE</small><p>Product thinking, information architecture, UX flows, interface design and development handoff.</p></div><div><small>RESPONSIBILITIES / KRA</small><p>Define the experience, balance user value with lead generation, document states and interactions, align implementation and own design QA.</p></div><div><small>CORE USERS</small><p>Students and working professionals who want quick, understandable resume feedback.</p></div></div>
    <div className="case-chapter"><span>02 / THE CHALLENGE</span><h3>A number alone does not help someone improve.</h3><p>The experience needed to explain what the score meant, identify weak areas without overwhelming the user, and guide them towards the next useful action. It also had to earn enough trust for a user to share their resume and details.</p></div>
    <div className="story-strip"><div><small>USER QUESTION</small><b>“Will this actually help my resume?”</b></div><div><small>DESIGN RESPONSE</small><b>Show useful feedback before asking for the next commitment.</b></div><div><small>BUSINESS VALUE</small><b>Build trust first, then create a qualified conversion moment.</b></div></div>
    <div className="journey-flow"><span>Landing page</span><i>→</i><span>Understand the value</span><i>→</i><span>Upload resume</span><i>→</i><span>Processing & trust cues</span><i>→</i><span>ATS score</span><i>→</i><span>Keyword & quality gaps</span><i>→</i><span>Improvement actions</span><i>→</i><span>Contextual lead CTA</span></div>
    <div className="case-chapter"><span>03 / KEY STATES & FLOWS</span><h3>Every state had to keep the user informed and moving.</h3><p>I mapped the first visit, file upload, validation errors, analysis, score reveal and improvement journey. The result experience separates the overall score from keyword gaps, formatting checks and content quality so users can understand what to fix first. Micro-conversion prompts appear after value has been demonstrated—not before.</p></div>
    <div className="decision-grid"><div><b>01</b><h4>Make value visible early</h4><p>A clear promise, resume visual and three-step flow reduce uncertainty before upload.</p></div><div><b>02</b><h4>Turn analysis into action</h4><p>Score insights, keyword feedback, quality heatmaps and improvement guidance make the result usable.</p></div><div><b>03</b><h4>Convert without interrupting</h4><p>Forms and CTAs appear at natural decision points rather than competing with the core task.</p></div></div>
    <div className="case-outcome"><span>04 / DESIGNED EXPERIENCE</span><p>Banner and upload flow → trust-building explanation → three-step process → detailed result page → score insights and keyword gaps → contextual conversion moments.</p><strong>Success signals I own with the team</strong><p>Upload completion, result-page engagement, CTA conversion, lead quality, repeat scans and implementation quality across screen sizes.</p><a className="outcome-link" href="https://atsresumechecker.jaroeducation.com/" target="_blank" rel="noreferrer">Explore the live ATS Resume Checker ↗</a></div>
   </div>
  </article>

  <article id="case-landing-pages" className="case case-paper">
   <div className="case-rail"><span>CASE STUDY 02</span><b>LP</b><small>Experience ownership<br/>Design operations<br/>Delivery system</small></div>
   <div className="case-body"><a className="case-close" href="#work" aria-label="Close Landing Page Ecosystem case study">Close ×</a>
    <div className="case-hero"><span>01 / THE SYSTEM</span><h2>Designing pages was only half the <em>problem.</em></h2><p>Landing pages moved across campaign, content, design and development teams. The real challenge was building clarity around requirements, approvals, ownership, priority and QA—while continuing to deliver responsive experiences at speed.</p></div>
    <div className="case-facts"><div><small>MY ROLE</small><p>End-to-end landing-page owner across requirements, UI/UX, handoff, QA, launch and post-launch improvements.</p></div><div><small>RESPONSIBILITIES / KRA</small><p>Prioritise work, assign and track developer tasks, review delivery, manage dependencies, maintain visibility and protect experience quality.</p></div><div><small>TEAM & STAKEHOLDERS</small><p>Campaign, content, SEO, marketing, internal developers and a three-member external development team.</p></div></div>
    <div className="flow"><span>Requirement</span><i>→</i><span>Content</span><i>→</i><span>Design</span><i>→</i><span>Review</span><i>→</i><span>Development</span><i>→</i><span>QA & launch</span></div>
    <div className="reference-links"><b>SELECTED LIVE REFERENCES</b><a href="https://amityonline.jaroeducation.com/bca-in-fintech-and-ai/" target="_blank" rel="noreferrer">Amity BCA — FinTech & AI ↗</a><a href="https://www.symbiosismba.jaroeducation.com/" target="_blank" rel="noreferrer">Symbiosis Online MBA ↗</a><a href="https://symbiosismscdatascience.jaroeducation.com/" target="_blank" rel="noreferrer">Symbiosis MSc Data Science ↗</a><a href="https://manipaljaipur.jaroeducation.com/" target="_blank" rel="noreferrer">Manipal Jaipur ↗</a><a href="https://www.jaroeducation.com/jkshah" target="_blank" rel="noreferrer">JK Shah ↗</a></div>
    <div className="story-strip"><div><small>BEFORE</small><b>Scattered briefs, late content and fragmented feedback.</b></div><div><small>INTERVENTION</small><b>P1–P3 priorities, clear owners, consolidated reviews and visible handoffs.</b></div><div><small>AFTER</small><b>A repeatable system from requirement to launch and maintenance.</b></div></div>
    <div className="case-chapter"><span>02 / MY APPROACH</span><h3>Turn repeated coordination into a visible operating system.</h3><p>I introduced structured intake, priority tags, consolidated feedback, clearer handoffs, SLA thinking and shared trackers. Alongside design ownership, I help manage the developer team: translate requirements into tasks, assign work by business priority, follow up on timelines and hours, review implementation, surface blockers and coordinate QA before launch.</p></div>
    <div className="decision-grid"><div><b>01</b><h4>One complete brief</h4><p>Final content, references, page type, owner and deadline arrive before execution starts.</p></div><div><b>02</b><h4>Visible development ownership</h4><p>I break work into tasks, align priorities, track progress and review responsive implementation with the developers.</p></div><div><b>03</b><h4>One source of truth</h4><p>Trackers and Jira make priorities, capacity, owners, hours, status and blockers visible.</p></div></div>
    <div className="case-outcome"><span>03 / IMPACT</span><p>A clearer, repeatable delivery model; stronger accountability across teams; better visibility for stakeholders; and more space for me to focus on experience quality instead of chasing fragmented updates.</p></div>
    <div className="tracker-map"><div><small>MY OPERATING SYSTEM</small><h3>Brief → Priority → Owner → Hours → Review → QA</h3><p>The tracker and Jira give me one view across DLP, premium and campaign work. I use them to allocate developer tasks, monitor capacity and progress, follow up on blockers, consolidate reviews and keep design-to-development delivery accountable.</p></div><div className="status-board"><span>PRIORITISATION</span><span>TEAM ALLOCATION</span><span>DELIVERY TRACKING</span><span>DESIGN QA</span></div></div>
    <div className="visual-heading"><span>04 / SELECTED LIVE WORK</span><h3>Different institutions. One adaptable conversion system.</h3><p>Real first-fold captures from pages I designed and delivered with campaign, content and development partners.</p></div>
    <div className="showcase-grid">
     <a href="https://amityonline.jaroeducation.com/bca-in-fintech-and-ai/" target="_blank" rel="noreferrer"><img src="/showcase/amity-bca.png" alt="Amity BCA in FinTech and AI landing page" loading="lazy"/><b>Amity BCA — FinTech & AI</b><small>Programme positioning · Responsive conversion</small></a>
     <a href="https://www.symbiosismba.jaroeducation.com/" target="_blank" rel="noreferrer"><img src="/showcase/symbiosis-mba.png" alt="Symbiosis Online MBA landing page" loading="lazy"/><b>Symbiosis Online MBA</b><small>Brand translation · Lead journey</small></a>
     <a href="https://www.symbiosisbca.jaroeducation.com/" target="_blank" rel="noreferrer"><img src="/showcase/symbiosis-bca.png" alt="Symbiosis BCA landing page" loading="lazy"/><b>Symbiosis BCA</b><small>Information hierarchy · Campaign UX</small></a>
     <a href="https://symbiosismscdatascience.jaroeducation.com/" target="_blank" rel="noreferrer"><img src="/showcase/symbiosis-msc.png" alt="Symbiosis MSc Data Science landing page" loading="lazy"/><b>Symbiosis MSc Data Science</b><small>Technical content · Visual clarity</small></a>
     <a href="https://manipaljaipur.jaroeducation.com/" target="_blank" rel="noreferrer"><img src="/showcase/manipal-jaipur.png" alt="Manipal Jaipur landing page" loading="lazy"/><b>Manipal Jaipur</b><small>Programme ecosystem · Scalable modules</small></a>
     <a href="https://www.iimtiruchirappalli.jaroeducation.com/post-graduate-certificate-in-senior-management-programme/" target="_blank" rel="noreferrer"><img src="/showcase/iim-trichy.png" alt="IIM Tiruchirappalli senior management programme page" loading="lazy"/><b>IIM Tiruchirappalli</b><small>Executive audience · Premium positioning</small></a>
     <a href="https://www.jaroeducation.com/jkshah" target="_blank" rel="noreferrer"><img src="/showcase/jk-shah.png" alt="JK Shah programme landing page" loading="lazy"/><b>JK Shah</b><small>Campaign landing page · Conversion focus</small></a>
    </div>
   </div>
  </article>

  <article id="case-jaro-connect" className="case case-lilac">
   <div className="case-rail"><span>CASE STUDY 03</span><b>2.0</b><small>Product ideation<br/>Platform strategy<br/>Feature design</small></div>
   <div className="case-body"><a className="case-close" href="#work" aria-label="Close Jaro Connect case study">Close ×</a>
    <div className="case-hero"><span>01 / SHIPPED FOUNDATION</span><h2>I designed the learner app—then explored what it could become <em>next.</em></h2><p>Phase 1 established Jaro Connect as a live educational platform across iOS and Android. I led the complete UI/UX journey: flows, wireframes, design system, high-fidelity screens and close coordination with developers for implementation.</p></div>
    <div className="case-facts"><div><small>MY ROLE</small><p>End-to-end mobile UI/UX, user flows, wireframes, design system, prototypes and developer collaboration.</p></div><div><small>RESPONSIBILITIES / KRA</small><p>Translate business requirements into journeys, maintain UI consistency, prepare developer-ready screens and review implementation.</p></div><div><small>PRODUCT OWNERSHIP</small><p>Phase 1 delivery plus opportunity framing, feature concepts and role-based journeys for the next ecosystem.</p></div></div>
    <figure className="product-proof"><img src="/showcase/jaro-connect-appstore.png" alt="Jaro Connect live App Store listing and mobile screens" loading="lazy"/><figcaption><b>LIVE PRODUCT EVIDENCE</b><span>App Store listing and shipped mobile experience.</span><a href="https://apps.apple.com/in/app/jaroconnect/id6447189924" target="_blank" rel="noreferrer">App Store ↗</a><a href="https://play.google.com/store/apps/details?id=com.newest.jaroeducation" target="_blank" rel="noreferrer">Google Play ↗</a></figcaption></figure>
    <div className="story-strip"><div><small>PHASE 1</small><b>Learning, community, jobs, chat and learner profiles.</b></div><div><small>MY DELIVERY</small><b>Flows → wireframes → design system → UI → development coordination.</b></div><div><small>PHASE 2 VISION</small><b>Turn course access into an ongoing career-progress ecosystem.</b></div></div>
    <div className="feature-cloud"><span>Referral wallet</span><span>Levels & rewards</span><span>Job-match score</span><span>AI counselling</span><span>Interview practice</span><span>Skill badges</span><span>Hiring analytics</span><span>Role dashboards</span></div>
    <div className="case-chapter"><span>02 / PRODUCT THINKING</span><h3>Features needed to reinforce one another—not become a crowded menu.</h3><p>I grouped ideas around four user outcomes: discover an opportunity, understand readiness, improve skills and take action. Role-based dashboards then surface only the most relevant next step for each user.</p></div>
    <div className="decision-grid"><div><b>01</b><h4>Make progress tangible</h4><p>Match scores, badges and step-based preparation show users where they are and what to do next.</p></div><div><b>02</b><h4>Create return loops</h4><p>Referrals, rewards, jobs and practice give learners reasons to return after completing a course.</p></div><div><b>03</b><h4>Design for the ecosystem</h4><p>Learner value connects with hiring insights, business onboarding and internal visibility.</p></div></div>
    <div className="case-outcome"><span>03 / PRODUCT EVOLUTION</span><p>The shipped foundation proves delivery across design and development. The next step is to validate the highest-value career use cases, map feasibility with the team and prioritise a focused MVP rather than shipping every concept together.</p><div className="store-actions"><a className="outcome-link" href="https://play.google.com/store/apps/details?id=com.newest.jaroeducation" target="_blank" rel="noreferrer">Google Play ↗</a><a className="outcome-link" href="https://apps.apple.com/in/app/jaroconnect/id6447189924" target="_blank" rel="noreferrer">App Store ↗</a></div></div>
   </div>
  </article>
  <article id="case-notion-ga4" className="case case-mint">
   <div className="case-rail"><span>CASE STUDY 04</span><b>AI</b><small>Automation<br/>Analytics ops<br/>AI synthesis</small></div>
   <div className="case-body"><a className="case-close" href="#work" aria-label="Close Notion and GA4 case study">Close ×</a>
    <div className="case-hero"><span>01 / THE OPERATIONS PROBLEM</span><h2>Reporting lived in dashboards. Decisions lived somewhere <em>else.</em></h2><p>I designed a weekly reporting system that brings GA4 performance into the team&apos;s Notion workspace, enriches it with programme context and generates a concise AI-assisted readout.</p></div>
    <div className="case-facts"><div><small>MY ROLE</small><p>Workflow design, data mapping, troubleshooting and reusable reporting structure.</p></div><div><small>RESPONSIBILITIES / KRA</small><p>Define reporting logic, connect tools, validate fields, handle exceptions and keep insights understandable for stakeholders.</p></div><div><small>STACK & OUTPUT</small><p>GA4, Make, Notion API and Gemini producing structured weekly records with editable summaries.</p></div></div>
    <div className="pipeline" aria-label="Analytics automation pipeline"><div><small>01</small><b>GA4</b><span>Sessions · Users · Views · Bounce</span></div><i>→</i><div><small>02</small><b>Make</b><span>Fetch · map · transform</span></div><i>→</i><div><small>03</small><b>Notion</b><span>Programme · URL · date · metrics</span></div><i>→</i><div><small>04</small><b>Gemini</b><span>Weekly narrative · next actions</span></div></div>
    <div className="database-mock"><div className="db-head"><b>Weekly landing-page intelligence</b><span>WORKFLOW RECONSTRUCTION</span></div><div className="db-row"><b>Report</b><b>Sessions</b><b>Users</b><b>Pageviews</b><b>AI summary</b></div><div className="db-row"><span>Amity Online MBA · Week 28</span><span>Mapped</span><span>Mapped</span><span>Mapped</span><span>Performance story + actions</span></div><div className="db-row"><span>Symbiosis BCA · Week 28</span><span>Mapped</span><span>Mapped</span><span>Mapped</span><span>Performance story + actions</span></div></div>
    <div className="story-strip"><div><small>FRICTION</small><b>Metrics were available, but assembling the weekly story was manual.</b></div><div><small>SYSTEM</small><b>One schema joins the page, programme, domain, period and performance.</b></div><div><small>HUMAN CONTROL</small><b>AI drafts the interpretation; raw evidence stays visible and editable.</b></div></div>
    <div className="case-chapter"><span>02 / SYSTEM THINKING</span><h3>The hard part was not the automation. It was designing dependable context.</h3><p>I resolved missing data-source visibility, pageview mapping, URL property conflicts, date ranges and multi-domain reporting. Prompt variables were mapped at both workflow and model stages so the summary could explain the data instead of merely repeating it.</p></div>
    <div className="decision-grid"><div><b>01</b><h4>Design the schema first</h4><p>Report, date, sessions, users, views, bounce rate, programme, URL, domain and AI summary form one reusable record.</p></div><div><b>02</b><h4>Keep evidence editable</h4><p>Raw metrics remain visible beside the generated interpretation, so teams can review and refine the narrative.</p></div><div><b>03</b><h4>Build for many domains</h4><p>Programme and domain context make the same workflow useful across a broad landing-page ecosystem.</p></div></div>
    <div className="case-outcome"><span>03 / RESULT</span><p>A working GA4 → Notion → Gemini pipeline and a repeatable reporting pattern that reduces manual assembly while keeping the strategy conversation close to the evidence.</p></div>
   </div>
  </article>
  <article id="case-mixtape" className="case case-mixtape">
   <div className="case-rail"><span>EXPLORATION 01</span><b>MIX</b><small>Mobile product<br/>UX research<br/>UI design</small></div>
   <div className="case-body"><a className="case-close" href="#archive-title" aria-label="Close Mixtape case study">Close ×</a>
    <div className="case-hero"><span>01 / THE IDEA</span><h2>Music streaming as a canvas for <em>creative community.</em></h2><p>Mixtape explored a social platform where personalised playlists, visual art and emerging creators could coexist—moving beyond passive listening towards expression and discovery.</p></div>
    <div className="case-facts"><div><small>MY CONTRIBUTION</small><p>Concept development, research, early web exploration, wireframes and mobile interface design as part of a collaborative project.</p></div><div><small>RESPONSIBILITIES / KRA</small><p>Frame the concept, define core journeys, translate the visual world into usable screens and prototype the discovery experience.</p></div><div><small>TOOLS</small><p>Figma, Illustrator, Photoshop, After Effects and Canva.</p></div></div>
    <div className="case-chapter"><span>02 / THE EXPERIENCE</span><h3>Let every playlist feel personal before the first song plays.</h3><p>The concept combines music discovery with original artwork and community participation. Early website ideas helped establish the visual world before the experience evolved into a mobile application.</p></div>
    <div className="journey-flow mixtape-flow"><span>Choose interests</span><i>→</i><span>Discover a mix</span><i>→</i><span>Open playlist story</span><i>→</i><span>Listen & react</span><i>→</i><span>Follow creator</span><i>→</i><span>Create a mixtape</span><i>→</i><span>Add artwork</span><i>→</i><span>Publish & share</span></div>
    <div className="case-chapter"><span>03 / CORE FLOWS</span><h3>Discovery and creation form one continuous loop.</h3><p>The listener journey starts with taste and mood, then moves through artwork-led discovery, playlist context and social response. The creator journey reverses that path: select tracks, shape a narrative, add original artwork, preview the mix and publish it to the community. Profiles connect listening identity with the mixes a person creates, saves and supports.</p></div>
    <div className="decision-grid"><div><b>01</b><h4>Music plus art</h4><p>Artwork is treated as part of the listening identity, not merely album decoration.</p></div><div><b>02</b><h4>Discovery through people</h4><p>The social layer creates space for emerging musicians, artists and shared taste.</p></div><div><b>03</b><h4>Prototype to learn</h4><p>Low-fidelity flows and a first interface draft made gaps visible for the next iteration.</p></div></div>
    <div className="case-outcome"><span>04 / REFLECTION</span><p>Mixtape was an early exercise in connecting a strong visual idea with product structure. The strongest opportunity is the create–discover–connect loop; the next iteration would validate onboarding, playlist creation effort, social motivation and content hierarchy with users.</p><a className="outcome-link" href="https://www.behance.net/gallery/186082403/Mixtape" target="_blank" rel="noreferrer">View the original Behance project ↗</a></div>
   </div>
  </article>
  <article id="case-kanine" className="case case-kanine">
   <div className="case-rail"><span>EXPLORATION 02</span><b>MARS</b><small>Gaming website<br/>UI/UX<br/>Visual design</small></div>
   <div className="case-body"><a className="case-close" href="#archive-title" aria-label="Close Kanine Klans case study">Close ×</a>
    <div className="case-hero"><span>01 / THE WORLD</span><h2>A Martian expedition designed to feel <em>playable.</em></h2><p>Kanine Klans is an immersive website concept for a Mars-based gaming experience. The goal was to translate the atmosphere of exploration into a clear interface without losing the cinematic energy of the game world.</p></div>
    <div className="case-facts"><div><small>MY CONTRIBUTION</small><p>Visual direction, interface design and the UX thinking supporting the landing-page journey.</p></div><div><small>FORMAT</small><p>Responsive gaming website concept focused on presenting the experience and building curiosity.</p></div><div><small>TOOLS</small><p>Figma, Illustrator, Photoshop and Canva.</p></div></div>
    <div className="case-chapter"><span>02 / DESIGN APPROACH</span><h3>Use atmosphere to guide attention—not bury the interface.</h3><p>The UI balances a futuristic Mars aesthetic with recognisable content structure, giving the player enough story and visual intrigue while keeping navigation and calls to action understandable.</p></div>
    <div className="decision-grid"><div><b>01</b><h4>Cinematic entry</h4><p>Strong space imagery and contrast establish the expedition before detailed information appears.</p></div><div><b>02</b><h4>Interface clarity</h4><p>Structured content blocks keep the visual universe engaging without becoming confusing.</p></div><div><b>03</b><h4>Consistent world-building</h4><p>Colour, texture and UI treatment work together to sustain the Martian theme.</p></div></div>
    <div className="case-outcome"><span>03 / REFLECTION</span><p>This project strengthened my ability to translate a fictional world into a usable digital surface. A next iteration would validate navigation, responsive behaviour and conversion moments with gamers.</p><a className="outcome-link" href="https://www.behance.net/gallery/186120675/Kanine-verse-UI-Project" target="_blank" rel="noreferrer">View the original Behance project ↗</a></div>
   </div>
  </article>
 </section>
 <section className="archive pad" aria-labelledby="archive-title">
  <div className="archive-head"><span>EARLIER EXPLORATIONS / BEHANCE</span><h1 id="archive-title">Where play became<br/><em>product thinking.</em></h1><p>Selected concept projects that show my visual range, early UX process and willingness to experiment.</p></div>
  <div className="archive-grid">
   <article className="archive-card mixtape-card"><a className="archive-open" href="#case-mixtape"><div className="archive-art"><span>MIX</span><i>PLAY ↗</i><span>TAPE</span></div><div className="archive-info"><small>MOBILE APP · UX RESEARCH · UI DESIGN</small><h2>Mixtape</h2><p>A social platform where personalised playlists and original artwork meet—designed as a creative community for music enthusiasts and emerging artists.</p><b>Open case study ↗</b></div></a><a className="behance-link" href="https://www.behance.net/gallery/186082403/Mixtape" target="_blank" rel="noreferrer">View Mixtape on Behance ↗</a></article>
   <article className="archive-card kanine-card"><a className="archive-open" href="#case-kanine"><div className="archive-art"><span>MARS</span><i>EXPLORE ↗</i><span>04</span></div><div className="archive-info"><small>GAMING WEBSITE · UI/UX · VISUAL DESIGN</small><h2>Kanine Klans</h2><p>An immersive Mars-expedition gaming website concept combining a cinematic space aesthetic with a clear, engaging interface.</p><b>Open case study ↗</b></div></a><a className="behance-link" href="https://www.behance.net/gallery/186120675/Kanine-verse-UI-Project" target="_blank" rel="noreferrer">View Kanine Klans on Behance ↗</a></article>
  </div>
 </section>
 <section id="about" className="about pad"><div><span className="flower">✿</span><h1>Not just making<br/>things <em>pretty.</em></h1></div><div className="about-copy"><h2>I turn complex requirements into digital experiences people can understand—and businesses can use.</h2><p>My work stretches beyond screens. I bring structure to briefs, align content and stakeholders, translate ideas into responsive experiences, partner with developers, and stay through QA and launch.</p><p>That end-to-end ownership is pulling me deeper into product thinking: defining the right problem, connecting decisions to outcomes, and helping teams ship with clarity.</p><div className="tools">Figma · GA4 · Mixpanel · Notion · Jira · AI prototyping</div></div></section>
 <section className="journey pad" aria-labelledby="journey-title"><div className="journey-head"><span>EXPERIENCE & EDUCATION</span><h1 id="journey-title">Built through<br/><em>ownership.</em></h1></div><div className="timeline"><article><span>NOW</span><div><small>JARO EDUCATION · MUMBAI</small><h2>Senior Executive — UI/UX & Product Designer</h2><p>Owning landing-page experiences end to end, designing product and AI-led tools, shaping mobile-product ideas, coordinating stakeholders and partnering with developers through QA and launch.</p><b>Product design · Conversion UX · Design operations · AI workflows</b></div></article><article><span>FOUNDATION</span><div><small>NATIONAL INSTITUTE OF FASHION TECHNOLOGY</small><h2>Bachelor&apos;s in Fashion Communication</h2><p>A multidisciplinary foundation in visual communication, research, storytelling and user-centred design that continues to shape how I solve product problems.</p><b>Communication design · Visual systems · Research · Storytelling</b></div></article></div></section>
 <section className="process pad"><span>HOW I WORK</span><div>{[["01","Find the real problem","Align people, context, constraints and the business priority."],["02","Make it make sense","Shape flows, content and interfaces into one coherent experience."],["03","Stay until it ships","Partner through handoff, responsive implementation, QA and launch."]].map(x=><article key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{x[2]}</p></article>)}</div></section>
 <footer id="contact" className="pad"><p>HAVE A PRODUCT, PROBLEM OR POSSIBILITY?</p><h1>Let&apos;s make an<br/><em>impact.</em></h1><div className="links"><a href="https://www.behance.net/jasmeetkaur7535" target="_blank">Behance ↗</a><a href="https://tile-player-82953827.figma.site/" target="_blank">Previous portfolio ↗</a><a href="#top">Back to top ↑</a></div><small>JASMEET KAUR · PRODUCT DESIGNER · MUMBAI</small></footer>
 </main>}
